// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3G-nCq6HWqSjw5qh9DVVt6wddSGJJr4',
    appId: '1:44522108351:web:980e04e8683d1de0265d0a',
    messagingSenderId: '44522108351',
    projectId: 'toppanapplication',
    authDomain: 'toppanapplication.firebaseapp.com',
    storageBucket: 'toppanapplication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfCPeVF8amAGuHIJ_OU4k16nGfUancens',
    appId: '1:44522108351:android:d095f44d521232ef265d0a',
    messagingSenderId: '44522108351',
    projectId: 'toppanapplication',
    storageBucket: 'toppanapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVabfEiERCayTvEoKpGWLCrRdwKF5BXB4',
    appId: '1:44522108351:ios:3c86ad44ff369756265d0a',
    messagingSenderId: '44522108351',
    projectId: 'toppanapplication',
    storageBucket: 'toppanapplication.firebasestorage.app',
    iosBundleId: 'com.toppan.mobilehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVabfEiERCayTvEoKpGWLCrRdwKF5BXB4',
    appId: '1:44522108351:ios:3c86ad44ff369756265d0a',
    messagingSenderId: '44522108351',
    projectId: 'toppanapplication',
    storageBucket: 'toppanapplication.firebasestorage.app',
    iosBundleId: 'com.toppan.mobilehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy3G-nCq6HWqSjw5qh9DVVt6wddSGJJr4',
    appId: '1:44522108351:web:308032e79b2843ca265d0a',
    messagingSenderId: '44522108351',
    projectId: 'toppanapplication',
    authDomain: 'toppanapplication.firebaseapp.com',
    storageBucket: 'toppanapplication.firebasestorage.app',
  );
}
